### ISSUE TITLE
Thanks for your tests

### ISSUE THREAD

**Issue by DelazJ** [Gustry/QGIS#5]
### What is the bug or the crash?

Just an attempt to see how https://github.com/qgis/QGIS/pull/44033 would render

### Steps to reproduce the issue

1. Click on '...'
1. Scroll down to '...'
1. See error

### Versions

QGIS 3.22 ( I know I do not comply with your instructions. Sorry!)

### Additional context

Just to say: "thanks for looking into this".

**Comment by Gustry** [comment]
Welcome !
